Set guava version to fit Hadoop requirements
Hadoop is using an old version of Guava lib (11.0.2), using a more recent version of Guava lib will cause a NoSuchMethodError on ComparisonChain.compare(boolean, boolean) that have changed on Guava 12.0.